name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          script-path: build.cake